import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { serifItalic, serif, logo } from "@/fonts/fonts";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const sans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        serif.variable,
        serifItalic.variable,
        logo.variable,
        "font-sans",
        sans.variable,
      )}
    >
      <body className="min-h-screen font-sans flex flex-col bg-background text-foreground dark:bg-background dark:text-foreground">
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
